### ISSUE TITLE
USER STORY: view paginated list of items  

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#1]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **view a list of items** so that I can **choose an item to check**

**Acceptance Criteria**
- [x] the user can view a list of items
- [x] the user can scroll down for more items

**Tasks**
- [x] create and design main page with list of items
- [x] create item add to the page when scrolling down functionality
- [x] test the scrolling down functionality
