### ISSUE TITLE
USER STORY: read messages

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#10]
EPIC: Messages

USER STORY:
As a **registered user / manager** I can **read the messages between me and the manager of the item post** so that I can **contact the manager privately**

**Acceptance Criteria**
- [ ] the user can successfully view and read the messages   
- [ ] the user is directed to the registration form if he is not registered  
- [ ] only the user and the manager can view the messages

**Tasks**
- [ ] create and design a message form
- [ ]wire the form to the database
- [ ] test the output of the messages
