### ISSUE TITLE
USER STORY: create an item

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#11]
EPIC: Items CRUD

USER STORY:
As a **manager** I can **create an item post with text and images** so that I can **show my items to other users**

**Acceptance Criteria**
- [x] the user can successfully post an item

**Tasks**
- [x] create and design a posting form
- [x] make the form able to upload text and images 
- [x] validate user input
- [x] wire the form to the database
- [x] test if the entries in the database was created
