### ISSUE TITLE
USER STORY: update an item

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#12]
EPIC: Items CRUD

USER STORY:
As a **manager** I can **update an item post** so that I can **change the content of the post**

**Acceptance Criteria**
- [x] the user can successfully update the information in an item post

**Tasks**
- [x] using the posting form to change the information in a post
- [x] make the form able to upload text and images 
- [x] validate user input
- [x] wire the form to the database
- [x] test if the entries in the database updated
