### ISSUE TITLE
USER STORY: delete an item

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#13]
EPIC: Items CRUD

USER STORY:
As a **manager** I can **delete an item post** so that I can **manage my content**

**Acceptance Criteria**
- [x] the user can successfully delete a post
- [x] the user is prompted to confirm the process

**Tasks**
- [x] add a delete button to the item post
- [x] create and design warning modal
- [x] wire the button to the database
- [x] test if the item was deleted from the database
