### ISSUE TITLE
USER STORY: create drafts

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#14]
EPIC: Items CRUD

USER STORY:
As a **manager** I can **create a draft item post** so that I can **post it later if not finished**

**Acceptance Criteria**
- [x] the user can successfully create a draft post
- [x] the user can publish the post later

**Tasks**
- [x] make the form able to save the post as a draft 
- [x] validate user input
- [x] wire the form to the database
- [x] test if the entries in the database matches
