### ISSUE TITLE
USER STORY: approve comments

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#15]
EPIC: Items CRUD

USER STORY:
As an **admin** I can **approve the comments on items posts I created** so that I can **filter the comments**

**Acceptance Criteria**
- [x] the Admin can approve comments
- [x] the comment can be viewed after approval
- [x] the User can not submit new comments unless previous comment approved
**Tasks**
- [x] add an approve functionality the comments 
- [x] test if the entries in the database matches
