### ISSUE TITLE
USER STORY: View number of comments

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#16]
EPIC: Item Interaction

USER STORY:
As an **unregistered user / registered user / manager** I can **view the number of comments for the item** so that I can **check popular items**

**Acceptance Criteria**
- [x] the user can view number of comments on each item

**Tasks**
- [x] create a counter beside the comments icon
- [x] link the counter to the database
- [x] test if the number of comments  is correct
