### ISSUE TITLE
USER STORY: search for an item

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#17]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **search items by title** so that I can **find the item I need**

**Acceptance Criteria**
- [x] the user can find items through search bar
- [x] the user can view a list of items he searched for 

**Tasks**
- [x] create and design a search bar
- [x] create the functionality to search items by title
- [x] create a page to list the results
- [x] test the download functionality
