### ISSUE TITLE
USER STORY: check featured post

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#18]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **click on a featured item post** so that I can **open the items page and check the information**

**Acceptance Criteria**
- [x] the user can open the featured item page by clicking on it
- [x] the user can view the information about the featured item 

**Tasks**
- [x] create and design a featured post layout
- [x] create the functionality to view the item by the number of likes 
- [x] test the business logic for choosing the post
