### ISSUE TITLE
USER STORY: view favorite items

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#19]
EPIC: View Items

USER STORY:
As a **registered user / manager** I can **click on favorite page** so that I can **check the items i have liked**

**Acceptance Criteria**
- [x] the user can open the favorite page by clicking on it
- [x] the user can view the items he liked 

**Tasks**
- [x] create and design a page for favorite items
- [x] create the functionality to view favorite items
- [x] test the business logic
