### ISSUE TITLE
USER STORY: view an item

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#2]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **click on an item** so that I can **open the items page and check the information**

**Acceptance Criteria**
- [x] the user can open the item page by clicking on it
- [x] the user can view the information about the item 

**Tasks**
- [x] create and design a page for the item
- [x] create the functionality to download the items data
- [x] test the download functionality
