### ISSUE TITLE
USER STORY: user page

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#20]
EPIC: View Items

USER STORY:
As a **manager** I can **click on my** so that I can **open my items page and be able to add, edit, and delete**

**Acceptance Criteria**
- [x] the user can open my page by clicking on it
- [x] the user can view the items he posted
- [x] the user can choose an action like add, edit and delete

**Tasks**
- [x] create and design my page
- [x] create CRUD functionality
- [x] test if the CRUD functionality is working properly
