### ISSUE TITLE
USER STORY: view items by category

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#21]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **click on a category** so that I can **view the items in that category**

**Acceptance Criteria**
- [x] the user can view a list of items in a category
- [x] the user can scroll down for more items

**Tasks**
- [x] create and design category page with list of items
- [x] create lazy loading items to the page when scrolling down functionality
- [x] test the scrolling down functionality 
- [x] test the category filtering logic
