### ISSUE TITLE
USER STORY: view items by tag

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#22]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **click on a tag** so that I can **view the items with that tag**

**Acceptance Criteria**
- [x] the user can view a list of items with a tag
- [x] the user can scroll down for more items

**Tasks**
- [x] create and design tag page with list of items
- [x] create lazy loading items to the page when scrolling down functionality
- [x] create tag functionality
- [x] test the scrolling down functionality 
- [x] test the tag logic
