### ISSUE TITLE
USER STORY: trending items

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#23]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **click on a trending post from a list** so that I can **view the item information**

**Acceptance Criteria**
- [x] the user can view a list of trending items in a list of 5
- [x] the items are sorted by the number of likes

**Tasks**
- [x] create and design list of trending items
- [x] test the items sorting logic
