### ISSUE TITLE
USER STORY: random items slider

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#24]
EPIC: View Items

USER STORY:
As a **unregistered user / registered user / manager** I can **view a slider of random items** so that I can **choose one of the items**

**Acceptance Criteria**
- [x] the user can view a slider of random items
- [x] the user can click on the slider info to open the item page

**Tasks**
- [x] create and design main page slider
- [x] create the logic to choose random items 
- [x] test the business logic
