### ISSUE TITLE
USER STORY: user registration

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#3]
EPIC: Registration / Login

USER STORY: user registration
As an **unregistered user** I can **register an account** so that I can **interact with other users or post my items**

**Acceptance Criteria**
- [x] the user can click on register to view registration form
- [x] the user can successfully register an account
- [x] the user can choose a role (manager or user)

**Tasks**
- [x] create and design the registration form 
- [x] create different rules for each role
- [x] validate the information input
- [x] add user successfully to database
