### ISSUE TITLE
USER STORY: user login

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#4]
EPIC: Registration / Login

USER STORY:
As a **registered user / manager** I can **login in to my account** so that I can **post items or leave comments, likes, messages**

**Acceptance Criteria**
- [x] the user can click on login and login into his account
- [x] the user can use the functionality for registered users

**Tasks**
- [x] create and design login form
- [x] validate user inputs
- [x] test login process
