### ISSUE TITLE
USER STORY: like / unlike

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#5]
EPIC: Item Interaction

USER STORY:
As a **registered user / manager** I can **click the like button** so that I can **like or unlike the item**

**Acceptance Criteria**
- [x] there is a like button in the item post
- [x]  the user can click the button to like or unlike the item

**Tasks**
- [x] create a like button 
- [x] toggle the value in the database
- [x] test the functionality of the button
