### ISSUE TITLE
USER STORY: view like numbers

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#6]
EPIC: Item Interaction

USER STORY:
As an **unregistered user / registered user / manager** I can **view the number of likes for the item** so that I can **check popular items**

**Acceptance Criteria**
- [x] the user can view number of likes on each item

**Tasks**
- [x] create a counter beside the like button
- [x] link the counter to the database
- [x] test if the number of likes is correct
