### ISSUE TITLE
USER STORY: read comments

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#7]
EPIC: Comments

USER STORY:
As an **unregistered user / registered user / manager** I can **view the comments on a post** so that I can **read users comments**

**Acceptance Criteria**
- [x] the user can view and read previous comments 

**Tasks**
- [x] create a comments form
- [x] wire the form to the database
- [x] test if the output is correct
