### ISSUE TITLE
USER STORY: leave a comment

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#8]
EPIC: Comments

USER STORY:
As a **registered user / manager** I can **leave a comment on an item post** so that I can **interact with other users**

**Acceptance Criteria**
- [x] the user can successfully leave a comment
- [x] the user is directed to the registration form if he is not registered  

**Tasks**
- [x] create and design a commenting form
- [x] validate the users input
- [x] create the functionality of writing the input to the database 
- [x] test the writing functionality
