### ISSUE TITLE
USER STORY: leave a message

### ISSUE THREAD

**Issue by AhmadAlmasriDev** [AhmadAlmasriDev/crafts-circle#9]
EPIC: Messages

USER STORY:
As a **registered user / manager** I can **leave a message to the manager of the item post** so that I can **contact the manager privately**

**Acceptance Criteria**
- [ ] the user can successfully write a message to the manager
- [ ] the user is directed to the registration form if he is not registered  
- [ ] only the user and the manager can view the messages

**Tasks**
- [ ] create and design a message form
- [ ] validate the users input
- [ ] create the functionality of writing the input to the database 
- [ ] test the writing functionality
